name: Deploy

on:
  push:
    branches:
      - dev-release

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{secrets.DEPLOY_PATH}}
          git checkout dev-release
          git pull origin dev-release
          forever restart $(forever list | grep wechat | cut -c24-27)
